return {
  -- {
  --   'echasnovski/mini.basics',
  --   version = false,
  --   opts = {
  --     -- Options. Set to `false` to disable.
  --     options = {
  --       basic = false,
  --       extra_ui = false,
  --       win_borders = 'double',
  --     },
  --     mappings = {
  --       basic = false,
  --       -- Prefix for mappings that toggle common options ('wrap', 'spell', ...).
  --       -- Supply empty string to not create these mappings.
  --       option_toggle_prefix = [[\]],
  --       -- Window navigation with <C-hjkl>, resize with <C-arrow>
  --       windows = false,
  --       move_with_alt = false,
  --     },
  --     -- Autocommands. Set to `false` to disable
  --     autocommands = {
  --       -- Basic autocommands (highlight on yank, start Insert in terminal, ...)
  --       basic = true,
  --
  --       -- Set 'relativenumber' only in linewise and blockwise Visual mode
  --       relnum_in_visual_mode = false,
  --     },
  --
  --     -- Whether to disable showing non-error feedback
  --     silent = false,
  --   }
  -- }
}
